<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>Principal</title>
    </head>

    <body>
        <ol>
            <li><a href="index.php?c=Usuarios&a=TodosUsuarios"> Mostrar todos los usuarios</a></li>
            <li><a href="index.php?c=Usuarios&a=save">Crear usuario</a></li>
            <li><a href="index.php?c=Notas&a=ListarTodasNotas">Mostrar notas</a></li>
            <li><a href="index.php?c=Notas&a=save">Crear nota</a></li>
        </ol>
    </body>
</html>