<h1>Insertar nota</h1>

<?=Utils::mostrarError('insert'); ?>
<form action="index.php?c=Notas&a=save" method="POST">
    <label for="usuario">Usuario</label>
    <input type="number" name="usuario" required/>

    <label for="titulo">Titulo</label>
    <input type="text" name="titulo" required/>

    <label for="descripcion">Descripcion</label>
    <textarea name="descripcion" required></textarea>

    <input type="submit" name="submit" value="Crear"/>
</form>